#version: '3'
services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - net1

  backend:
    image: backend:1.0
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - net1
  frontend:
    image: nginx:1.27.0
    container_name: frontend
    networks:
      - net1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html

networks:
  net1:
    driver: bridge

